export const queryKeys = {
  facultys: "Fetch Facultys",
  faculty: "Get Faculty",
  user_positions: "Fetch Organize Chart",
  user_position: "Get Organize Chart",
  issues: "Fetch Issues",
  issue: "Get Issue",
  positions: "Fetch Positions",
  position: "Get Position",
  prioritys: "Fetch Priority",
  priority: "Get Priority",
  categories: "Fetch Categories",
  category: "Get Category",
  equip_statues: "Fetch Equip Status",
  equip_status: "Get Equip Status",
  statuses: "Fetch Status",
  status: "Get Status",
  users: "Fetch User",
  user: "Get User",
  provinces: "Fetch Province",
  amphure: "Get Amphure",
  tumbol: "Get tumbol",
  image: "Get Image",
  equipments: "Fetch Equipments",
  equipment: "Get Equipment",
  requests: "Fetch Requests",
  request: "Get Request",
};
